version: "3.6"
    
services:
  mongodb:
    image: mongo:5.0-focal
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: computers-api
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    
  redis:
    image: redis:7.0-rc-alpine3.15
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - 6379:6379
    
volumes:
  redis_data: {}
  mongodb_data: {}